### ISSUE TITLE
Mapsplice2 multi-thread error

### ISSUE THREAD

**Issue by ShobanaSekar** [grahamgower/MapSplice#2]
Hi,

I am running Mapsplice2 for some of our samples and keep running into the below error:

[Thu Oct 19 15:52:58 2017] Beginning Mapsplice run (MapSplice v2.1.8)
[Thu Oct 19 15:52:58 2017] Bin directory: /home/ssekar/tools/circRNA/dback_reinstalled/Mapsplice2/MapSplice-v2.1.8/bin/
[Thu Oct 19 15:52:58 2017] Preparing output location mapsplice_out/
[Thu Oct 19 15:52:58 2017] Checking files or directory: /scratch/ssekar/ADCC_circRNA_rerun/downsampled/ADCC_0001_PC_L02652.sub.proj/ADCC_0001_PC_L02652.sub.proj_R1.fastq
[Thu Oct 19 15:52:58 2017] Checking files or directory: /scratch/ssekar/ADCC_circRNA_rerun/downsampled/ADCC_0001_PC_L02652.sub.proj/ADCC_0001_PC_L02652.sub.proj_R2.fastq
[Thu Oct 19 15:52:58 2017] Checking files or directory: /home/ssekar/splitFastas/
[Thu Oct 19 15:52:58 2017] Checking Bowtie index files
[Thu Oct 19 15:52:58 2017] Inspecting Bowtie index files
[Thu Oct 19 15:52:58 2017] Checking reference sequence length
[Thu Oct 19 15:53:05 2017] Checking consistency of Bowtie index and reference sequence
[Thu Oct 19 15:53:05 2017] Checking read format
-----[Read Format: FASTQ]
-----[Read Type: Pair End]
-----[Total # Reads: 85547262]
-----[Max Read Length: 83]
-----[Min Read Length: 83]
-----[Max Quality Score: 74]
-----[Min Quality Score: 35]
-----[Quality Score Scale: Phred+33]
[Thu Oct 19 15:54:07 2017] Running MapSplice multi-thread
[MapSplice Running Failed]
Error: Running MapSplice multi-thread failed:  -11

My python version is 2.7.3 with the following packages:
numpy
pysam
scipy
pybedtools
pandas
HTSeq

Not sure if am missing any packages?

Appreciate your help!

Shobana

**Comment by grahamgower** [comment]
Hi Shobana,
This is an old fork of mapsplice, which was not properly debugged. I recommend trying a more recent version, from the upstream repository (http://www.netlab.uky.edu/p/bioinfo/MapSplice2). If your problems persist, then you should submit a report to the upstream developers.
-Graham

**Comment by ShobanaSekar** [comment]
Sorry I wasn't clear, I am running Mapsplice2 and getting this error. I have emailed mapsplice@netlab.uky.edu, hopefully that is the right group to contact?

Thanks,
Shobana

**Comment by grahamgower** [comment]
I think that's right. I am not a MapSplice developer, just a rogue programmer that happened to make some changes to mapsplice some years ago. I've not used it in 3 years.
